# Generated by Django 2.1 on 2019-01-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canopyapp', '0003_auto_20190108_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'verbose_name_plural': 'Booking Status'},
        ),
        migrations.AlterModelOptions(
            name='bookingstatuscategory',
            options={'verbose_name_plural': 'Booking Status Categories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chargecategory',
            options={'verbose_name_plural': 'Charge Categories'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name_plural': 'Maintenance'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name_plural': 'Product Prices'},
        ),
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
