# Generated by Django 2.1 on 2019-01-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopyapp', '0004_auto_20190108_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='datetime_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='datetime_to',
            field=models.DateTimeField(),
        ),
    ]
