# Generated by Django 2.1 on 2019-01-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canopyapp', '0006_auto_20190110_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
    ]
