# Generated by Django 2.1 on 2019-01-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canopyapp', '0007_auto_20190110_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canopyapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete='CASCADE', to='canopyapp.Cart')),
                ('product', models.ForeignKey(null=True, on_delete='CASCADE', to='canopyapp.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='bookingstatus',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='bookingstatus',
            name='booking_status',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingStatus',
        ),
    ]
