# Generated by Django 2.1 on 2019-01-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canopyapp', '0008_auto_20190111_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='charge_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_category', to='canopyapp.ChargeCategory'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='canopyapp.Product'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='canopyapp.Product'),
        ),
    ]
