# Generated by Django 2.1 on 2019-01-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='customer.Customer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('DF', 'Default'), ('HR', 'Hourly'), ('DY', 'Daily'), ('WK', 'Weekly')], default='DF', max_length=2)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pickupdatetime', models.DateTimeField()),
                ('dropdatetime', models.DateTimeField()),
                ('order', models.ForeignKey(null=True, on_delete='CASCADE', related_name='order_orderitems', to='order.Order')),
                ('product', models.ForeignKey(null=True, on_delete='CASCADE', related_name='product_orderitems', to='product.Product')),
            ],
        ),
    ]
