# Generated by Django 2.1 on 2019-02-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
